### ISSUE TITLE
Curtain status in home app stuck in opening/closing

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-openapi#114]
**Describe Your Problem:**
Home app curtain status stuck in Opening / Closing. It doesn't matter what the real curtain status is. Other than that the curtain works good, and controls good in Home app.

**Logs:**

[2021-02-17, 2:39:07 p.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,100 commandType: command
[2021-02-17, 2:39:41 p.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,0 commandType: command

**Homebridge Config:**

{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 1200,
                "hide_device": [
                    "E416FECFBDEC",
                    "DC36EAA29B0F"
                ],
                "curtain": {
                    "set_minStep": 5,
                    "set_min": 2,
                    "set_max": 98
                }
            },
            "devicediscovery": false,
            "platform": "SwitchBot"
        }

**Screenshots:**
<a><img src="https://user-images.githubusercontent.com/48269361/108272385-62356480-712f-11eb-94cd-adb08ff33ade.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/48269361/108272606-b80a0c80-712f-11eb-86c7-09fa7f04a764.png" width="550px"></a>

**Device Model:**

Raspberry Pi 3
# **Environment:**

- **Node.js Version**: v14.15.5
- **NPM Version**: v7.5.4
- **Homebridge Version**: v1.1.7
- **Homebridge SwitchBot Plugin Version**: v3.1.0
- **Homebridge Config UI X Plugin Version**: v4.39.0
- **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@jonpeng can you post the curtain from the switchbot app?

**Comment by jonpeng** [comment]
@donavanbecker 
![image](https://user-images.githubusercontent.com/48269361/108398382-2d301d00-71d6-11eb-8926-39baf8aa6119.png)
![image](https://user-images.githubusercontent.com/48269361/108398404-3325fe00-71d6-11eb-99fb-312b1ac20eb6.png)

**Comment by donavanbecker** [comment]
@jonpeng can you click into the curtain so I can see the settings? and post screenshot.

**Comment by jonpeng** [comment]
@donavanbecker 
![image](https://user-images.githubusercontent.com/48269361/108413436-43df6f80-71e8-11eb-8125-0d3cef3c7e06.png)
![image](https://user-images.githubusercontent.com/48269361/108413519-5c4f8a00-71e8-11eb-8fff-45c34ae61f86.png)
![image](https://user-images.githubusercontent.com/48269361/108413547-62de0180-71e8-11eb-84cf-8d80c8ad2209.png)
![image](https://user-images.githubusercontent.com/48269361/108414211-32e32e00-71e9-11eb-91d3-73f9e7d53265.png)
![image](https://user-images.githubusercontent.com/48269361/108414227-37a7e200-71e9-11eb-957e-ee7619b5c7a2.png)
![image](https://user-images.githubusercontent.com/48269361/108414303-4c847580-71e9-11eb-8016-3a03b220e3a5.png)

**Comment by donavanbecker** [comment]
Can you change set_max to 97?

**Comment by jonpeng** [comment]
set_max changed to 97. But no changes.

**Comment by donavanbecker** [comment]
okay I have had a chance to look at this. hoping the latest beta will fix this for you.
Can you test it out?

Beta: `v3.1.1-beta.12`

**Comment by donavanbecker** [comment]
should be fixed with v3.2.0, if not please open new issue.

I would recommend looking at curtain refreshRate config and also potentially recalibrating your curtains.

**Comment by jonpeng** [comment]
@donavanbecker 
v3.2.0 doesn't run correctly on Homebridge v1.2.5. Curtains show correctly in Home app, but can not control. Some IR devices no response. I couldn't update it to v1.3.0 due to one of my other plugins has issues with the new HB version. I will try later.

logs for your reference:
[2021-02-22, 10:43:48 a.m.] [SwitchBot] Discovered Bonus room TV box DIY Set Top Box
[2021-02-22, 10:43:48 a.m.] [SwitchBot] Adding new accessory: Bonus room TV box DIY Set Top Box DeviceID: 02-202102201102-20016768
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(Use `node --trace-warnings ...` to show where the warning was created)
(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).setProps(...).onSet is not a function
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/devices/curtains.js:53:14)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:471:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:219:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new TV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:55:77)
    at SwitchBotPlatform.createTV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new Light (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/irdevices/lights.js:34:73)
    at SwitchBotPlatform.createLight (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:627:17)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:275:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new TV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:55:77)
    at SwitchBotPlatform.createTV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new TV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:55:77)
    at SwitchBotPlatform.createTV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:9860) UnhandledPromiseRejectionWarning: TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new TV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/irdevices/tvs.js:55:77)
    at SwitchBotPlatform.createTV (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:550:13)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/dist/platform.js:254:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)

**Comment by donavanbecker** [comment]
As it states in the release notes, `Homebridge 1.3.0` is the new requirement for that version, you will need to roll back to `v3.1.0`, until you can get to `Homebridge 1.3.0`.

all of those errors are because `.onSet` and `.onGet` are features of `Homebridge 1.3.0`.

**Comment by jonpeng** [comment]
@donavanbecker 
Installed HB 1.3.0 and SB v3.2.0
The issue is still exist while fully open/close the curtain.

logs:
[2021-02-23, 8:34:43 a.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,5 commandType: command
[2021-02-23, 8:34:47 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:34:47 a.m.] [homebridge-switchbot-openapi] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 100 exceeded maximum of 99. See https://git.io/JtMGR for more info.
[2021-02-23, 8:34:52 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:35:20 a.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,15 commandType: command
[2021-02-23, 8:35:22 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:35:27 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:35:39 a.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,25 commandType: command
[2021-02-23, 8:35:42 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:35:47 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:36:05 a.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,100 commandType: command
[2021-02-23, 8:36:07 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:36:13 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:36:13 a.m.] [homebridge-switchbot-openapi] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[2021-02-23, 8:36:17 a.m.] [homebridge-switchbot-openapi] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 0 exceeded minimum of 1. See https://git.io/JtMGR for more info.
[2021-02-23, 8:38:41 a.m.] [SwitchBot] Sending request for Guest Room Curtain to SwitchBot API. command: setPosition parameter: 0,ff,0 commandType: command
[2021-02-23, 8:38:42 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:38:47 a.m.] [SwitchBot] Checking Guest Room Curtain Status ...
[2021-02-23, 8:38:47 a.m.] [homebridge-switchbot-openapi] This plugin generated a warning from the characteristic 'Current Position': characteristic was supplied illegal value: number 100 exceeded maximum of 99. See https://git.io/JtMGR for more info.

**Comment by donavanbecker** [comment]
did you recalibrate your curtains?

Also I have pushed a new beat to fix those warnings for the Curtain Position if you could test that to see if those still exist in the beta?

Beta: `3.2.1-beta.0`

**Comment by jonpeng** [comment]
Recalibration doesn't fix the issue. 
But beta 3.2.1-beta.1 fixed all issues including the warnings. 
Well done!

**Comment by donavanbecker** [comment]
@jonpeng nice! I will publish a version today when I can find time.

**Comment by donavanbecker** [comment]
v3.2.1 is released.
