### ISSUE TITLE
SwitchBot Curtain: set min and max does not work correctly

### ISSUE THREAD

**Issue by matclothier** [OpenWonderLabs/homebridge-switchbot-openapi#64]
I have 5 pairs of curtains and some of them report as 99% or 98% when closed not 100%, some also report as 1% or 2% open when fully opened. I have recalibrated them several times but it still does the same if I make sure they are full closed and open when calibrating. If I set the max and min at say 10 min and 90 max then when closed they show as fully closed but when open they only show as 90% open if the app shows then as 100% or 89% if the app shows 1% etc. So it seems the max is just deducted from the 100 so they never report as open. I hope that makes sense but let me know if you need more info.

Set max value for curtains is deducted from the total so they never report as fully open.

Put a value of less then 100 in the set max and see if the curtains report as fully opened when open.

It should just clip at the value so that anything over the max or min value is treated as 100 or 0 respectively.

[1/19/2021, 12:17:03 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[1/19/2021, 12:17:03 PM] [HB Supervisor] Started Homebridge v1.2.5 with PID: 12872
[1/19/2021, 12:17:04 PM] Loaded config.json with 0 accessories and 5 platforms.
[1/19/2021, 12:17:04 PM] ---
[1/19/2021, 12:17:04 PM] Loaded plugin: homebridge-ewelink@4.4.0
[1/19/2021, 12:17:04 PM] Registering platform 'homebridge-ewelink.eWeLink'
[1/19/2021, 12:17:04 PM] ---
[1/19/2021, 12:17:05 PM] Loaded plugin: homebridge-ring@9.14.1
[1/19/2021, 12:17:05 PM] Registering platform 'homebridge-ring.Ring'
[1/19/2021, 12:17:05 PM] ---
[1/19/2021, 12:17:05 PM] Loaded plugin: homebridge-switchbot-openapi@2.0.0
[1/19/2021, 12:17:05 PM] Registering platform 'homebridge-switchbot-openapi.SwitchBot'
[1/19/2021, 12:17:05 PM] ---
[1/19/2021, 12:17:05 PM] Loaded plugin: @milo526/homebridge-tuya-web@0.7.1
[1/19/2021, 12:17:05 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[1/19/2021, 12:17:05 PM] ---
[1/19/2021, 12:17:05 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/19/2021, 12:17:05 PM] Registering platform 'homebridge-config-ui-x.config'
[1/19/2021, 12:17:05 PM] ---
[1/19/2021, 12:17:05 PM] Loading 5 platforms...
[1/19/2021, 12:17:05 PM] [Config] Initializing config platform...
[1/19/2021, 12:17:05 PM] [Config] Running in Service Mode
[1/19/2021, 12:17:05 PM] [Ring] Initializing Ring platform...
[1/19/2021, 12:17:05 PM] [eWeLink] Initializing eWeLink platform...
[1/19/2021, 12:17:05 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[1/19/2021, 12:17:05 PM] [SwitchBot] Initializing SwitchBot platform...
[1/19/2021, 12:17:05 PM] [SwitchBot] Using Default Refresh Rate.
[1/19/2021, 12:17:05 PM] [SwitchBot] Loading accessory from cache: Thomas’s Curtains Curtain
[1/19/2021, 12:17:05 PM] [SwitchBot] Loading accessory from cache: Family Room Window Curtains Curtain
[1/19/2021, 12:17:05 PM] [SwitchBot] Loading accessory from cache: Bedroom Curtains Curtain
[1/19/2021, 12:17:05 PM] [SwitchBot] Loading accessory from cache: Family Room Door Curtains Curtain
[1/19/2021, 12:17:05 PM] [SwitchBot] Loading accessory from cache: William’s Curtain’s Curtain
[1/19/2021, 12:17:06 PM] Homebridge v1.2.5 is running on port 53257.
["pr","pw","ev"]}
[1/19/2021, 12:17:06 PM] [TuyaWebPlatform] [Light Strip] Characteristic.Saturation - {"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}
[1/19/2021, 12:17:06 PM] [TuyaWebPlatform] Enable cloud polling with interval 605s
[1/19/2021, 12:17:06 PM] [SwitchBot] Total Devices Found: 16
[1/19/2021, 12:17:06 PM] [SwitchBot] Discovered Thomas’s Curtains Curtain
[1/19/2021, 12:17:06 PM] [SwitchBot] Restoring existing accessory from cache: Thomas’s Curtains Curtain DeviceID: E24CC7CA35DA
[1/19/2021, 12:17:06 PM] [SwitchBot] Discovered Family Room Window Curtains Curtain
[1/19/2021, 12:17:06 PM] [SwitchBot] Restoring existing accessory from cache: Family Room Window Curtains Curtain DeviceID: EAAB715B13CC
[1/19/2021, 12:17:06 PM] [SwitchBot] Discovered Bedroom Curtains Curtain
[1/19/2021, 12:17:06 PM] [SwitchBot] Restoring existing accessory from cache: Bedroom Curtains Curtain DeviceID: F0E76D5CB2F8
[1/19/2021, 12:17:06 PM] [SwitchBot] Discovered Family Room Door Curtains Curtain
[1/19/2021, 12:17:06 PM] [SwitchBot] Restoring existing accessory from cache: Family Room Door Curtains Curtain DeviceID: F143E0220AF8
[1/19/2021, 12:17:07 PM] [SwitchBot] Discovered a Hub Mini
[1/19/2021, 12:17:07 PM] [SwitchBot] Discovered William’s Curtain’s Curtain
[1/19/2021, 12:17:07 PM] [SwitchBot] Restoring existing accessory from cache: William’s Curtain’s Curtain DeviceID: FE79A5AFE650

**Homebridge Config:**

        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "E92EF4978312",
                    "E6902E18119E",
                    "E42EEEE9E487",
                    "FA32C091BB79",
                    "D8C42407D4D4"
                ],
                "curtain": {
                    "set_min": 10,
                    "set_max": 90
                }
            },
            "platform": "SwitchBot"
        }

**Screenshots:**

SwitchBot Curtain Rod

# **Environment:**

- **Node.js Version**: 
- **NPM Version**: 
- **Homebridge Version**: 
- **Homebridge SwitchBot Plugin Version**:
- **Homebridge Config UI X Plugin Version**:
- **Operating System**:

**Comment by donavanbecker** [comment]
@matclothier, I have corrected this in the latest beta. Can you test it out let let me know how it works?

You will not have to change your config at all.
Beta `v2.0.1-beta.6`

**Comment by matclothier** [comment]
Just checked and it is exactly the same, sorry.

**Comment by donavanbecker** [comment]
@matclothier, I tested this multiple times and it was working as expected with the changes in the beta.

Can you report back after a few days and let me know if you are still experiencing this?

Also if you are, can you post a screenshot of the SwitchBot App and Home App.

**Comment by matclothier** [comment]
I have tried everything and it is definitely refreshed but still the same.  I have the max set to 90% and when the curtain is 0% (fully open) on the API it shows as 10% open in homebridge.  I do get an error that I am not on the beta of homebridge, if that has any impact?

The plugin "homebridge-switchbot-openapi" requires a Homebridge version of >=1.3.0-beta.47 which does not satisfy the current Homebridge version of 1.2.5. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

**Comment by donavanbecker** [comment]
@matclothier No that is mistake for not taking it out.

As for the Max and Min, I will have to figure out a way for this to display probably. Might not be out in the next release.

I would recommend Calibrating your curtains again.

**Comment by matclothier** [comment]
If I calibrate so that it goes to 100% then they don’t fully close so that isn’t an option. The rod ones are a bit of a pain. Can you not just say that if the value is between max and 100 then override it to 100 and same for min and 0?

**Comment by matclothier** [comment]
OK, I have done some more testing today.  It is working better but still not right.  With max set to 90% and no min set at all, when the curtains are open they now show as fully open but when closed they show as closed in the homebridge interface but closing with the details showing 10% open in the apple home app.  Any suggestions?

**Comment by donavanbecker** [comment]
@matclothier I am going to keep on working on this. I have experienced what you are talking about, so I just need to figure out a way to approach it. Might take a little bit.

**Comment by matclothier** [comment]
Great thanks. Let me know if you want me to test anything or when there is a new beta to test

**Comment by nyjklein** [comment]
If I may, I'm having similar issues. Since I upgraded to 2.4.1 this morning, I'm now getting a series of these messages in the log whenever I open or close the curtains from the Homebridge interface even after I've recalibrated:
[21/01/2021, 09:41:19] [SwitchBot] Your Curtains need to be recalibrated
[21/01/2021, 09:41:20] [SwitchBot] Your Curtains need to be recalibrated
[21/01/2021, 09:41:21] [SwitchBot] Your Curtains need to be recalibrated

**Comment by donavanbecker** [comment]
> If I may, I'm having similar issues. Since I upgraded to 2.1.0 this morning, I'm now getting a series of these messages in the log whenever I open or close the curtains from the Homebridge interface or the Home app even after I've recalibrated:
> [21/01/2021, 09:41:19] [SwitchBot] Your Curtains need to be recalibrated
> [21/01/2021, 09:41:20] [SwitchBot] Your Curtains need to be recalibrated
> [21/01/2021, 09:41:21] [SwitchBot] Your Curtains need to be recalibrated

Can you please open another issue for this?

**Comment by nyjklein** [comment]
Again, sorry for jumping into someone else's bug. But I'm really unclear on what the min and max options are meant to do and how that will solve my issue.

My basic issue, is that even when the curtains are sent the fully open or fully closed command, they seem to "rebound" and end up at 2% or 98% , Thus the Homebridge/Homekit status never ends up fully open or closed. Perhaps this is a bug or the nature of the switchbot firmware. But no matter how many times I've tried recalibrating, it always ends up this way. I've tried using the min and max settings but they only seem to affect what command is sent to the curtains for open and close. 

Perhaps, if there was a "tolerance" value (either fixed or settable) to change the status to 0% or 100% when the returned position is within that tolerance (e.g. 5% or 95%). I know it's a bit kludgy, but I think it would bypass this weirdness.

Thanks for listening.

**Comment by donavanbecker** [comment]
@matclothier And @nyjklein can you test the latest beta and let me know if it is working for you now?

**Comment by donavanbecker** [comment]
Nvm let me look into this further.

**Comment by nyjklein** [comment]
I see you're still working on this but I wanted to add a couple of pictures to clarify the issue from my perspective. 

This is what HomeKit shows: 
![Screenshot 2021-02-02 at 9 00 11 AM](https://user-images.githubusercontent.com/76184316/106612099-bab51100-6536-11eb-988b-8c13e5d5bef7.png)

Even though the SwitchBot shows app the status as "fully closed":
![Screenshot 2021-02-02 at 9 14 55 AM](https://user-images.githubusercontent.com/76184316/106612753-70805f80-6537-11eb-9a78-af539005300f.png)

![Screenshot 2021-02-02 at 9 02 06 AM](https://user-images.githubusercontent.com/76184316/106612212-dcae9380-6536-11eb-8fdc-6a93b3d25288.png)

P.S. I'm on v2.1.1-beta.4

Jeff

**Comment by donavanbecker** [comment]
@matclothier And @nyjklein can you try  Beta:`v2.1.1-beta.7`?

**Comment by nyjklein** [comment]
Upgraded to v2.1.1-beta.7. I'm now seeing this weird error:

node:28359) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'set_minStep' of undefined
    at new Curtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/Devices/Curtain.ts:75:57)
    at SwitchBotPlatform.createCurtain (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:519:9)
    at SwitchBotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-switchbot-openapi/src/platform.ts:216:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by donavanbecker** [comment]
@nyjklein No this shouldn't haven't to be inputted.

**Comment by nyjklein** [comment]
When I set a value for min step, that error goes away. When I clear it to default, the error comes back.

Jeff

**Comment by matclothier** [comment]
No, still the same in Apple home stuck on closing or opening.  In accessories in Homebridge it was showing as fully closed or open but not any more.

**Comment by donavanbecker** [comment]
@matclothier and @nyjklein can you give Beta: `v2.1.1-beta.14` a try?

**Comment by matclothier** [comment]
still looks exactly the same to me.

**Comment by donavanbecker** [comment]
> still looks exactly the same to me.

Can you clear activity on just your curtain accessory from homebridge UI? You don't have to clear all of  your homebridge accessories.

**Comment by nyjklein** [comment]
A bit different for me. But back to where I think the production version was. 

First, the issue in earlier betas with the error when min step is defaulted is fixed.

It still has the "rebound" issue, i.e. when you close or open the curtain it initially reflects "fully" and details show 0% or 100%. But when the refresh occurs, the status then shows **2% open** when it's really **closed** and **98% open** when it's really open. 

But homekit status now matches what's in homebridge and is no longer stuck on closing. 

Jeff

P.S. Could you please clarify the actual intent of the three settings?

**Comment by nyjklein** [comment]
I removed the curtain cached accessory, restarted, and the curtain was discovered and added back.

I'm seeing the same behavior described in the update just above.

Jeff

**Comment by donavanbecker** [comment]
> I removed the curtain cached accessory, restarted, and the curtain was discovered and added back.
> 
> I'm seeing the same behavior described in the update just above.
> 
> Jeff

I am really sorry @nyjklein, this is working as expected for me...
<a><img src="https://user-images.githubusercontent.com/9875439/106928557-ec65dd80-66d8-11eb-89e3-d0e8cc979a8d.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/9875439/106928460-d0623c00-66d8-11eb-9dc8-653ae2ac2315.png" width="250px"></a>
<a><img src="https://user-images.githubusercontent.com/9875439/106928458-cfc9a580-66d8-11eb-9a2b-eeea77299147.png" width="250px"></a><a><img src="https://user-images.githubusercontent.com/9875439/106928454-ce987880-66d8-11eb-8377-35c501263fcd.png" width="250px"></a>

This is my config:
```json
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "*********************",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "***************"
                ],
                "bot": {
                    "device_switch": [
                        "***************"
                    ],
                    "device_press": [
                        "***************",
                        "***************",
                        "***************"
                    ]
                },
                "humidifier": {
                    "set_minStep": 20
                },
                "curtain": {
                    "set_minStep": 20,
                    "set_min": 1,
                    "set_max": 99
                }
            },
            "platform": "SwitchBot"
        }
```

**Comment by matclothier** [comment]
Not for me:
![20210204_171147000_iOS](https://user-images.githubusercontent.com/55290749/106929605-78ddc380-670c-11eb-835a-7b6df55dda77.png)
![20210204_171207000_iOS](https://user-images.githubusercontent.com/55290749/106929612-7aa78700-670c-11eb-9d33-542fb8bfcfb6.png)
![20210204_171222000_iOS](https://user-images.githubusercontent.com/55290749/106929617-7c714a80-670c-11eb-8470-62f2f364c9f4.png)

            "name": "SwitchBot",
            "credentials": {
                "openToken": "****",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "hide_device": [
                    "****",
                    "****",
                    "****",
                    "****",
                    "****"
                ],
                "curtain": {
                    "set_minStep": 20,
                    "set_min": 1,
                    "set_max": 99
                }
            },
            "platform": "SwitchBot"
        }

**Comment by donavanbecker** [comment]
@matclothier What version of homebridge are you using?

**Comment by matclothier** [comment]
1.2.5

**Comment by donavanbecker** [comment]
> 1.2.5

can you try `v1.3.0-beta.50`

**Comment by matclothier** [comment]
I’m running it on docker on my Synology NAS. Any idea how I install the beta version?

**Comment by donavanbecker** [comment]
> I’m running it on docker on my Synology NAS. Any idea how I install the beta version?

Are you using Homebridge UI?

**Comment by nyjklein** [comment]
**Adjusting my settings on v2.1.1-beta.14 now works correctly for me!!!**

I have:
                "curtain": {
                    "set_minStep": 20,
                    "set_min": 2,
                    "set_max": 98
                }
And that seems to fix my issue with open and close! My status in Homebridge and the Home app now correctly reflect "fully open" and "fully closed". Hoorah !

Donavan, thanks very much!

P.S. I'm running Homebridge V1.1.7:
![hb](https://user-images.githubusercontent.com/76184316/106944869-1f1dcf00-66f5-11eb-8193-dc00c6d4b8eb.png)

**Comment by matclothier** [comment]
I didn’t get a chance to update but this morning it all seems to be working perfectly. Thanks for all the efforts on this
